import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vania's First Website &lt;3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#8052c1] to-[#ffffff]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-bold tracking-tight text-[color:white]
           sm:text-[5rem]">
            Welcome to <span className="text-[hsl(279,100%,64%)]">Vania</span>'s Website!
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/resume"
              
            >
              <h3 className="text-2xl font-bold">Resume →</h3>
              <div className="text-lg">
                Updated August 2023
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Portfolio →</h3>
              <div className="text-lg">
                My marketing projects, articles, writings, design and email marketing portfolio.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
